project:
  type: website
  output-dir: docs

website:
  title: "Hüseyin Emre Bacak's Analytics Lab"
  navbar:
    search: false
    left:
      - text: About Me
        href: about.qmd
      - text: My Posts
        href: posts.qmd
      - text: "EMU660 Coursework"
        menu:
          - text: Assignments
            href: assignments.qmd
          - text: Project
            href: project.qmd
            
    tools:
      - icon: github
        href: https://github.com/hemrebacak
      - icon: linkedin
        href: https://www.linkedin.com/in/hemre-bacak/

  sidebar:
    - title: "Assignments"
      style: "docked"
      search: true
      contents:
        - assignments.qmd
        - assignments/assignment-1.qmd
        - assignments/assignment-2.qmd
  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    center: "Hacettepe IE - EMU660 - Spring 2026" 
    border: true
format:
  html:
    toc: true
    toc-location: left
    theme: 
      - vapor
      - matrix.scss
    css: styles.css


editor: visual

